### ISSUE TITLE
Wrong attributes in CONFGENED state

### ISSUE THREAD

**Issue by AP1001** [hilanderas/powter-server#1]
# Wrong attributes in CONFGENED state
### Test environment
* ubuntu 18.04
* powter-server 0.1.3

### info file
```yml
dns-proxy:
  DNSPORT: 16350:16370
  WAN: eth0
sskcp:
  server:
 - key: test
    listenport: 4201
    log-dir: /home/ubuntu/log
    mode: sskcp
  - key: test
    listenport: 4202
    log-dir: /home/ubuntu/log
    mode: sskcp
  - key: test
    listenport: 4203
    log-dir: /home/ubuntu/log
    mode: sskcp
  - key: test
    listenport: 4204
    log-dir: /home/ubuntu/log
    mode: sskcp
```
### How to reproduce
```bash
make install
make update(modify info with syntax error)
```
### Actual results
* gen_config failed 
* State is running
* conf.queued exists
### Expected results
* gen_config failed 
* State is running
* conf.queued not exists
